version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports: ["27017:27017"]
  redis:
    image: redis:7
    restart: unless-stopped
    ports: ["6379:6379"]
  backend:
    build: ./backend
    command: npm run dev
    volumes:
      - ./backend:/usr/src/app
      - ./data/uploads:/data/uploads
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
  worker:
    build: ./backend
    command: npm run worker
    volumes:
      - ./backend:/usr/src/app
      - ./data/uploads:/data/uploads
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - mongo
    # ensure poppler-utils installed in Dockerfile
volumes:
  mongo-data:
